import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm db:types`.
    "lib/supabase/types.ts",
  ]),
  {
    // docs/03-security.md: the service-role key never reaches client code.
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "Program:has(ExpressionStatement[directive='use client']) MemberExpression[property.name=/SERVICE_ROLE/]",
          message:
            "The service-role key is server-only; never read it in a client component.",
        },
      ],
    },
  },
]);

export default eslintConfig;
